# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: [ workflow_dispatch ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  custom_js_action_job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Custom js Action Demo

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: First js action step
        id:   myjsaction
        uses: odnman/demojsaction@v1
        with: 
          name-of-you: 'Michael Michael'
      # Use the output from the `myjsaction` step 
      - name: Get the output message time
        run:  echo "The time was ${{ steps.myjsaction.outputs.time }}"
